# Generated by Django 5.0.1 on 2024-02-23 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Floors",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "create",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object create", verbose_name="Create time"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object update", verbose_name="Update time"
                    ),
                ),
                ("name", models.CharField(max_length=400, verbose_name="Название")),
                ("number", models.IntegerField(verbose_name="Floor number")),
            ],
            options={
                "verbose_name": "Floor",
                "verbose_name_plural": "Floors",
                "db_table": "floors",
                "ordering": ("-update",),
                "get_latest_by": "-update",
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "create",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object create", verbose_name="Create time"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object update", verbose_name="Update time"
                    ),
                ),
                ("name", models.CharField(max_length=400, verbose_name="Название")),
                ("number", models.IntegerField(verbose_name="Office number")),
                ("floor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.floors")),
            ],
            options={
                "verbose_name": "Office",
                "verbose_name_plural": "Offices",
                "db_table": "offices",
                "ordering": ("-update",),
                "get_latest_by": "-update",
            },
        ),
        migrations.CreateModel(
            name="Door",
            fields=[
                (
                    "create",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object create", verbose_name="Create time"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object update", verbose_name="Update time"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Door name")),
                ("number", models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name="Door number")),
                ("office", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.office")),
            ],
            options={
                "verbose_name": "Door data",
                "verbose_name_plural": "Doors data",
                "db_table": "doors",
                "ordering": ("-update",),
                "get_latest_by": "-update",
            },
        ),
    ]
