# Generated by Django 5.0.1 on 2024-02-23 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessCenter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "create",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object create", verbose_name="Create time"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object update", verbose_name="Update time"
                    ),
                ),
                ("name", models.CharField(max_length=400, verbose_name="Floor name")),
            ],
            options={
                "verbose_name": "Business center",
                "verbose_name_plural": "Business centers",
                "db_table": "business_center",
                "ordering": ("-update",),
                "get_latest_by": "-update",
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "create",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object create", verbose_name="Create time"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object update", verbose_name="Update time"
                    ),
                ),
                ("name", models.CharField(max_length=400, verbose_name="Floor name")),
                ("number", models.IntegerField(verbose_name="Floor number")),
                (
                    "business_center",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organizations.businesscenter"),
                ),
            ],
            options={
                "verbose_name": "Floor",
                "verbose_name_plural": "Floors",
                "db_table": "floors",
                "ordering": ("-update",),
                "get_latest_by": "-update",
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "create",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object create", verbose_name="Create time"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object update", verbose_name="Update time"
                    ),
                ),
                ("name", models.CharField(max_length=400, verbose_name="Office name")),
                ("number", models.IntegerField(verbose_name="Office number")),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.floor",
                        verbose_name="Floor name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Office",
                "verbose_name_plural": "Offices",
                "db_table": "offices",
                "ordering": ("-update",),
                "get_latest_by": "-update",
            },
        ),
        migrations.CreateModel(
            name="Door",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "create",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object create", verbose_name="Create time"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of object update", verbose_name="Update time"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Door name")),
                ("number", models.PositiveIntegerField(verbose_name="Door number")),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.office",
                        verbose_name="Office name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Door",
                "verbose_name_plural": "Doors",
                "db_table": "doors",
                "ordering": ("-update",),
                "get_latest_by": "-update",
            },
        ),
    ]
