# Generated by Django 5.0.1 on 2024-02-23 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Floors",
            new_name="Floor",
        ),
    ]
